### PR TITLE
Matchplot extension

### PR DESCRIPTION
**Pull request by SynapticSage**
Matchplot for 2D timeseries.

Made a matchplot variant to check dtw of 2D animal paths (x,y,t) onto templated "ideal" paths. Plots (x,y) of each curve in the pair and lines to corresponding times. 

Call the recipe like the 1D `matchplot`
```julia
matchplot2(Q, Y, ds=5)
```

Circles example
circle  

Path example
paths

### CODE REVIEW

**Comment by baggepinnen** [comment]
Hello and thanks for this cool PR :) 
Would you mind calling the plotting function from the tests as well? Testing plots is difficult, but we can at least test that the plot function does not throw an error. You could add a line similar to this one that tests the standard `matchplot` https://github.com/baggepinnen/DynamicAxisWarping.jl/blob/master/test/runtests.jl#L153

It would also be good to mention the new function in the documentation in the readme.

**Comment by SynapticSage** [comment]
Sounds good. I'll push these changes soon when I catch some free time later this week.

**Comment by SynapticSage** [comment]
Threw a short section into the Readme.md, a function header doc, and a few tests around the line you recommended.

Also added two keyword args to the plot. It's nice to be able to have the index plotted onto a 3rd axis or toggle normalization off sometimes. So options to toggle those.

**Comment by SynapticSage** [comment]
Anything that would be helpful to finish off this PR?

**Comment by baggepinnen** [comment]
Thanks for your patience :) it had just fallen off my radar

**Comment by SynapticSage** [comment]
No worries! Also fell off mine. 

Take care :)

**Pull request merged**
